# Generated by Django 6.0.4 on 2026-04-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_appointment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentSlot',
            new_name='Slot',
        ),
    ]
